ARG APP_DOCKER_BASE_IMAGE="X"
FROM ${APP_DOCKER_BASE_IMAGE} AS installer
RUN pnpm run build
FROM nginx:1.27.0 AS runner
WORKDIR /app
COPY --from=installer /app/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=installer /app/out /var/www/out