services:
  hooore-generator:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        - APP_DOCKER_BASE_IMAGE=${APP_DOCKER_BASE_IMAGE}
    env_file:
      - path: ./.env
        required: true
    environment:
      - APP_DOCKER_BASE_IMAGE=${APP_DOCKER_BASE_IMAGE}
      - PG_URL=${PG_URL}
      - PROJECT_ID=${PROJECT_ID}
      - NEXT_PUBLIC_UMAMI_ID=${NEXT_PUBLIC_UMAMI_ID}
      - NEXT_PUBLIC_UMAMI_URL=${NEXT_PUBLIC_UMAMI_URL}
      - NEXT_PUBLIC_ICONIFY_API_URL=${NEXT_PUBLIC_ICONIFY_API_URL}
      - PORT=${PORT}
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "${PORT}:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 5s
      timeout: 5s
      retries: 5
